import { Metadata } from "next";
import { LoginProvider } from "@/contexts/LoginContext";
import { Poppins } from "next/font/google"

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[#FFFFF0] text-black`}
      >
        <LoginProvider>
          {children}
        </LoginProvider>
      </body>
    </html>
  )
}
