import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar"
import Sidebar from "@/components/Sidebar";
import PrivateRoute from "@/components/PrivateRoute";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FFFFF0] text-black`}
      >
        <PrivateRoute>
          <Navbar />
          <div className="grid w-full grid-cols-[.5fr_3fr]">
            <Sidebar />
            <div className="w-full h-full bg-[#E8E9ED] overflow-auto">
              {children}
            </div>
          </div>
        </PrivateRoute>
      </body>
    </html>
  );
}
